export interface DailySong {
  title: string
  artist: string
}

// Popular guitar songs drawn from UG's top charts across genres
const SONGS: DailySong[] = [
  { artist: 'Eagles', title: 'Hotel California' },
  { artist: 'Guns N Roses', title: 'November Rain' },
  { artist: 'The Beatles', title: 'Let It Be' },
  { artist: 'Ed Sheeran', title: 'Perfect' },
  { artist: 'Oasis', title: 'Wonderwall' },
  { artist: 'Nirvana', title: 'Come As You Are' },
  { artist: 'Johnny Cash', title: 'Hurt' },
  { artist: 'Bob Dylan', title: 'Knockin On Heavens Door' },
  { artist: 'John Denver', title: 'Take Me Home Country Roads' },
  { artist: 'The Beatles', title: 'Blackbird' },
  { artist: 'Metallica', title: 'Nothing Else Matters' },
  { artist: 'Eric Clapton', title: 'Wonderful Tonight' },
  { artist: 'Red Hot Chili Peppers', title: 'Californication' },
  { artist: 'Green Day', title: 'Good Riddance' },
  { artist: 'Pearl Jam', title: 'Black' },
  { artist: 'Tom Petty', title: 'Free Fallin' },
  { artist: 'The Rolling Stones', title: 'Angie' },
  { artist: 'Simon And Garfunkel', title: 'The Sound Of Silence' },
  { artist: 'Led Zeppelin', title: 'Stairway To Heaven' },
  { artist: 'Jack Johnson', title: 'Better Together' },
  { artist: 'Eric Clapton', title: 'Tears In Heaven' },
  { artist: 'Coldplay', title: 'The Scientist' },
  { artist: 'U2', title: 'With Or Without You' },
  { artist: 'Pink Floyd', title: 'Wish You Were Here' },
  { artist: 'David Bowie', title: 'Space Oddity' },
  { artist: 'Neil Young', title: 'Heart Of Gold' },
  { artist: 'Van Morrison', title: 'Brown Eyed Girl' },
  { artist: 'Fleetwood Mac', title: 'Landslide' },
  { artist: 'John Mayer', title: 'Gravity' },
  { artist: 'Ben Harper', title: 'Steal My Kisses' },
  { artist: 'Jason Mraz', title: 'Im Yours' },
  { artist: 'Ed Sheeran', title: 'The A Team' },
  { artist: 'Adele', title: 'Someone Like You' },
  { artist: 'Taylor Swift', title: 'Love Story' },
  { artist: 'Imagine Dragons', title: 'Demons' },
  { artist: 'Passenger', title: 'Let Her Go' },
  { artist: 'Hozier', title: 'Take Me To Church' },
  { artist: 'Radiohead', title: 'Creep' },
  { artist: 'The Lumineers', title: 'Ho Hey' },
  { artist: 'Mumford And Sons', title: 'The Cave' },
  { artist: 'Bon Iver', title: 'Skinny Love' },
  { artist: 'Nick Drake', title: 'Pink Moon' },
  { artist: 'James Taylor', title: 'Fire And Rain' },
  { artist: 'Cat Stevens', title: 'Wild World' },
  { artist: 'Paul Simon', title: 'Sound Of Silence' },
  { artist: 'Creedence Clearwater Revival', title: 'Have You Ever Seen The Rain' },
  { artist: 'Lynyrd Skynyrd', title: 'Simple Man' },
  { artist: 'The Eagles', title: 'Take It Easy' },
  { artist: 'The Doors', title: 'People Are Strange' },
  { artist: 'Jimi Hendrix', title: 'Hey Joe' },
  { artist: 'Bob Marley', title: 'Redemption Song' },
  { artist: 'Tracy Chapman', title: 'Fast Car' },
  { artist: 'Bruce Springsteen', title: 'The River' },
  { artist: 'Tom Waits', title: 'Downtown Train' },
  { artist: 'Elvis Presley', title: 'Love Me Tender' },
  { artist: 'Johnny Cash', title: 'Ring Of Fire' },
  { artist: 'Dolly Parton', title: 'Jolene' },
  { artist: 'Willie Nelson', title: 'On The Road Again' },
  { artist: 'Leonard Cohen', title: 'Hallelujah' },
  { artist: 'Gordon Lightfoot', title: 'Sundown' },
  { artist: 'Alanis Morissette', title: 'Ironic' },
  { artist: 'Sheryl Crow', title: 'If It Makes You Happy' },
  { artist: 'Jewel', title: 'Hands' },
  { artist: 'Dave Matthews Band', title: 'Crash Into Me' },
  { artist: 'REM', title: 'Losing My Religion' },
  { artist: 'The Smashing Pumpkins', title: 'Disarm' },
  { artist: 'Alice In Chains', title: 'Down In A Hole' },
  { artist: 'Soundgarden', title: 'Black Hole Sun' },
  { artist: 'Stone Temple Pilots', title: 'Creep' },
  { artist: 'Weezer', title: 'Island In The Sun' },
  { artist: 'Blink 182', title: 'Adam Song' },
  { artist: 'Foo Fighters', title: 'Best Of You' },
  { artist: 'The White Stripes', title: 'Hotel Yorba' },
  { artist: 'Jack White', title: 'Love Interruption' },
  { artist: 'Arctic Monkeys', title: 'Do I Wanna Know' },
  { artist: 'The Killers', title: 'Mr Brightside' },
  { artist: 'Coldplay', title: 'Yellow' },
  { artist: 'Keane', title: 'Somewhere Only We Know' },
  { artist: 'Snow Patrol', title: 'Chasing Cars' },
  { artist: 'Kings Of Leon', title: 'Use Somebody' },
  { artist: 'Muse', title: 'Blackout' },
  { artist: 'Blur', title: 'Song 2' },
  { artist: 'Pulp', title: 'Common People' },
  { artist: 'The Verve', title: 'The Drugs Dont Work' },
  { artist: 'Stereophonics', title: 'Dakota' },
  { artist: 'Franz Ferdinand', title: 'Take Me Out' },
  { artist: 'The Strokes', title: 'Last Nite' },
  { artist: 'Jack Johnson', title: 'Banana Pancakes' },
  { artist: 'John Mayer', title: 'Your Body Is A Wonderland' },
  { artist: 'Damien Rice', title: 'The Blower Daughter' },
  { artist: 'Iron And Wine', title: 'Flightless Bird' },
  { artist: 'Fleet Foxes', title: 'White Winter Hymnal' },
  { artist: 'The Tallest Man On Earth', title: 'The Garden' },
  { artist: 'City And Colour', title: 'The Girl' },
  { artist: 'Kodaline', title: 'All I Want' },
  { artist: 'Of Monsters And Men', title: 'Little Talks' },
  { artist: 'Vance Joy', title: 'Riptide' },
  { artist: 'Troye Sivan', title: 'Youth' },
  { artist: 'Ben Howard', title: 'Keep Your Head Up' },
  { artist: 'Jose Gonzalez', title: 'Heartbeats' },
  { artist: 'Nick Cave', title: 'Into My Arms' },
]

export function getSongOfTheDay(): DailySong {
  const dayIndex = Math.floor(Date.now() / 86_400_000)
  return SONGS[dayIndex % SONGS.length]
}
